# Generated by Django 4.1.5 on 2023-02-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_simpletest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleTest',
            new_name='SimpleModel',
        ),
    ]
